# Generated by Django 3.2.3 on 2021-05-30 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Twitter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("access_token_secret", models.CharField(max_length=255)),
                ("raw", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                (
                    "twitter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.twitter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
