# Generated by Django 3.2.3 on 2021-05-30 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_auto_20210530_2258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="twitter",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.twitter",
            ),
        ),
    ]
