# Generated by Django 3.0.5 on 2021-05-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_auto_20210530_2315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitter",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
