# Generated by Django 3.1.3 on 2020-11-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_auto_20201113_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='tag_name', max_length=25),
            preserve_default=False,
        ),
    ]
