# Generated by Django 3.1.3 on 2020-11-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0003_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='user',
            new_name='account',
        ),
    ]
